from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import check_cross_repo_release_gate as gate


def _init_repo(path: Path) -> None:
    path.mkdir(parents=True)
    subprocess.run(["git", "init"], cwd=path, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=path, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=path, check=True)
    (path / "README.md").write_text("# Test\n", encoding="utf-8")
    subprocess.run(["git", "add", "README.md"], cwd=path, check=True)
    subprocess.run(["git", "commit", "-m", "init"], cwd=path, check=True, capture_output=True)


def test_release_gate_reports_missing_repos(tmp_path: Path) -> None:
    report = gate.build_report(tmp_path)

    assert report["ok"] is False
    assert report["repos"]["nous-os"]["exists"] is False
    assert "repository missing" in report["repos"]["nous-os"]["issues"]


def test_release_gate_detects_dirty_repo(tmp_path: Path) -> None:
    repo = tmp_path / "nous-os"
    _init_repo(repo)
    (repo / "README.md").write_text("# Test\n\nchanged\n", encoding="utf-8")

    report = gate.build_report(tmp_path)

    assert report["repos"]["nous-os"]["exists"] is True
    assert report["repos"]["nous-os"]["dirty"] is True


def test_release_gate_scans_secret_like_tokens(tmp_path: Path) -> None:
    repo = tmp_path / "nous-os"
    _init_repo(repo)
    (repo / "docs").mkdir()
    (repo / "docs" / "bad.md").write_text("api_key = abcdefghijklmnopqrstuvwxyz123456\n", encoding="utf-8")

    report = gate.build_report(tmp_path)

    assert any("secret-like token" in issue for issue in report["repos"]["nous-os"]["issues"])


def test_release_gate_allows_documented_workspace_paths(tmp_path: Path) -> None:
    repo = tmp_path / "nous-os"
    _init_repo(repo)
    (repo / "docs").mkdir()
    (repo / "docs" / "paths.md").write_text(
        "Run with --workspace /Users/liyao/nousos for the local dev workspace.\n",
        encoding="utf-8",
    )

    report = gate.build_report(tmp_path)

    assert not any("private absolute path" in issue for issue in report["repos"]["nous-os"]["issues"])


def _init_trustmem_with_tracked_distilled(repo: Path) -> None:
    """Init a trustmem-like repo where knowledge/distilled/ is already tracked.

    Production trustmem has the directory committed; only NEW files inside
    appear as ``?? knowledge/distilled/<file>.md``. The test must mirror that
    layout, otherwise git folds the whole knowledge/ tree into ``?? knowledge/``.
    """
    repo.mkdir(parents=True)
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)
    (repo / "README.md").write_text("# Test\n", encoding="utf-8")
    (repo / "knowledge" / "distilled").mkdir(parents=True)
    (repo / "knowledge" / "distilled" / "seed.md").write_text("seed\n", encoding="utf-8")
    subprocess.run(["git", "add", "README.md", "knowledge/distilled/seed.md"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-m", "init"], cwd=repo, check=True, capture_output=True)


def _init_trustmem_with_runtime_lanes(repo: Path) -> None:
    _init_trustmem_with_tracked_distilled(repo)
    for directory in [
        repo / "agent-bus",
        repo / "data" / "episodes",
        repo / "knowledge" / "ai-infra",
        repo / "research" / "metrics",
    ]:
        directory.mkdir(parents=True, exist_ok=True)
    tracked_files = [
        repo / "agent-bus" / "handoff_queue.json",
        repo / "data" / "episodes" / "episodes.jsonl",
        repo / "research" / "metrics" / "citation_log.jsonl",
    ]
    for path in tracked_files:
        path.write_text("[]\n", encoding="utf-8")
    subprocess.run(
        ["git", "add", *(str(path.relative_to(repo)) for path in tracked_files)],
        cwd=repo,
        check=True,
    )
    subprocess.run(["git", "commit", "-m", "runtime lanes"], cwd=repo, check=True, capture_output=True)


def test_release_gate_allowlists_documented_noise_paths(tmp_path: Path) -> None:
    repo = tmp_path / "trustmem"
    _init_trustmem_with_tracked_distilled(repo)
    (repo / "knowledge" / "distilled" / "user-task-routine-output.md").write_text(
        "autogenerated distilled note\n", encoding="utf-8"
    )

    report = gate.build_report(tmp_path)
    trustmem = report["repos"]["trustmem"]

    assert trustmem["exists"] is True
    assert trustmem["dirty"] is False, (
        f"distilled knowledge files should be allowlisted, got dirty_entries={trustmem['dirty_entries']}"
    )
    assert trustmem["dirty_allowlisted_entries"], "allowlisted noise must still be visible"
    assert any("knowledge/distilled" in entry for entry in trustmem["dirty_allowlisted_entries"])


def test_release_gate_does_not_mask_real_dirty_when_mixed_with_noise(tmp_path: Path) -> None:
    repo = tmp_path / "trustmem"
    _init_trustmem_with_tracked_distilled(repo)
    (repo / "knowledge" / "distilled" / "note.md").write_text("noise\n", encoding="utf-8")
    (repo / "README.md").write_text("# Test\n\nreal change\n", encoding="utf-8")

    report = gate.build_report(tmp_path)
    trustmem = report["repos"]["trustmem"]

    assert trustmem["dirty"] is True, "real README change must still mark repo dirty"
    assert any("README.md" in entry for entry in trustmem["dirty_entries"])
    assert any("knowledge/distilled" in entry for entry in trustmem["dirty_allowlisted_entries"])
    assert trustmem["dirty_count"] == 1
    assert trustmem["dirty_allowlisted_count"] == 1


def test_release_gate_allowlists_trustmem_runtime_sediment(tmp_path: Path) -> None:
    repo = tmp_path / "trustmem"
    _init_trustmem_with_runtime_lanes(repo)
    (repo / "agent-bus" / "handoff_queue.json").write_text("[1]\n", encoding="utf-8")
    (repo / "data" / "episodes" / "episodes.jsonl").write_text("{}\n", encoding="utf-8")
    (repo / "data" / "episodes" / "episodes.jsonl.bak.20260430").write_text("backup\n", encoding="utf-8")
    (repo / "knowledge" / "ai-infra" / "promoted-chat-bot-note.md").write_text("note\n", encoding="utf-8")
    (repo / "research" / "metrics" / "citation_log.jsonl").write_text("{}\n", encoding="utf-8")

    report = gate.build_report(tmp_path)
    trustmem = report["repos"]["trustmem"]

    assert trustmem["dirty"] is False
    assert trustmem["dirty_count"] == 0
    assert trustmem["dirty_allowlisted_count"] == 5


def test_release_gate_does_not_truncate_large_git_status_output(tmp_path: Path) -> None:
    repo = tmp_path / "trustmem"
    _init_trustmem_with_tracked_distilled(repo)
    for index in range(120):
        (repo / "knowledge" / "distilled" / f"routine-{index:03d}.md").write_text(
            "noise\n",
            encoding="utf-8",
        )
    (repo / "README.md").write_text("# Test\n\nreal change\n", encoding="utf-8")

    report = gate.build_report(tmp_path)
    trustmem = report["repos"]["trustmem"]

    assert trustmem["dirty"] is True
    assert trustmem["dirty_count"] == 1
    assert trustmem["dirty_allowlisted_count"] == 120
    assert trustmem["dirty_entries"] == [" M README.md"]
    assert len(trustmem["dirty_allowlisted_entries"]) == 50


def test_release_gate_cli_json_shape(tmp_path: Path, capsys) -> None:
    code = gate.main(["--workspace", str(tmp_path), "--json"])
    out = capsys.readouterr().out
    payload = json.loads(out)

    assert code == 1
    assert "repos" in payload
    assert "nous-os" in payload["repos"]


class CrossRepoReleaseGateUnitTests(unittest.TestCase):
    """unittest coverage for CI, which runs `python -m unittest discover`."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.workspace = Path(self._tmp.name)

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def test_reports_missing_repos(self) -> None:
        report = gate.build_report(self.workspace)

        self.assertFalse(report["ok"])
        self.assertFalse(report["repos"]["nous-os"]["exists"])
        self.assertIn("repository missing", report["repos"]["nous-os"]["issues"])

    def test_detects_dirty_repo(self) -> None:
        repo = self.workspace / "nous-os"
        _init_repo(repo)
        (repo / "README.md").write_text("# Test\n\nchanged\n", encoding="utf-8")

        report = gate.build_report(self.workspace)

        self.assertTrue(report["repos"]["nous-os"]["exists"])
        self.assertTrue(report["repos"]["nous-os"]["dirty"])

    def test_scans_secret_like_tokens(self) -> None:
        repo = self.workspace / "nous-os"
        _init_repo(repo)
        (repo / "docs").mkdir()
        (repo / "docs" / "bad.md").write_text(
            "api_key = abcdefghijklmnopqrstuvwxyz123456\n",
            encoding="utf-8",
        )

        report = gate.build_report(self.workspace)

        self.assertTrue(any("secret-like token" in issue for issue in report["repos"]["nous-os"]["issues"]))

    def test_allowlists_documented_noise_paths(self) -> None:
        repo = self.workspace / "trustmem"
        _init_trustmem_with_tracked_distilled(repo)
        (repo / "knowledge" / "distilled" / "user-task-routine-output.md").write_text(
            "autogenerated distilled note\n",
            encoding="utf-8",
        )

        report = gate.build_report(self.workspace)
        trustmem = report["repos"]["trustmem"]

        self.assertFalse(trustmem["dirty"])
        self.assertEqual(trustmem["dirty_count"], 0)
        self.assertEqual(trustmem["dirty_allowlisted_count"], 1)
        self.assertTrue(any("knowledge/distilled" in entry for entry in trustmem["dirty_allowlisted_entries"]))

    def test_does_not_mask_real_dirty_when_mixed_with_noise(self) -> None:
        repo = self.workspace / "trustmem"
        _init_trustmem_with_tracked_distilled(repo)
        (repo / "knowledge" / "distilled" / "note.md").write_text("noise\n", encoding="utf-8")
        (repo / "README.md").write_text("# Test\n\nreal change\n", encoding="utf-8")

        report = gate.build_report(self.workspace)
        trustmem = report["repos"]["trustmem"]

        self.assertTrue(trustmem["dirty"])
        self.assertEqual(trustmem["dirty_count"], 1)
        self.assertEqual(trustmem["dirty_allowlisted_count"], 1)
        self.assertTrue(any("README.md" in entry for entry in trustmem["dirty_entries"]))

    def test_allowlists_trustmem_runtime_sediment(self) -> None:
        repo = self.workspace / "trustmem"
        _init_trustmem_with_runtime_lanes(repo)
        (repo / "agent-bus" / "handoff_queue.json").write_text("[1]\n", encoding="utf-8")
        (repo / "data" / "episodes" / "episodes.jsonl").write_text("{}\n", encoding="utf-8")
        (repo / "data" / "episodes" / "episodes.jsonl.bak.20260430").write_text("backup\n", encoding="utf-8")
        (repo / "knowledge" / "ai-infra" / "promoted-chat-bot-note.md").write_text("note\n", encoding="utf-8")
        (repo / "research" / "metrics" / "citation_log.jsonl").write_text("{}\n", encoding="utf-8")

        report = gate.build_report(self.workspace)
        trustmem = report["repos"]["trustmem"]

        self.assertFalse(trustmem["dirty"])
        self.assertEqual(trustmem["dirty_count"], 0)
        self.assertEqual(trustmem["dirty_allowlisted_count"], 5)

    def test_does_not_truncate_large_git_status_output(self) -> None:
        repo = self.workspace / "trustmem"
        _init_trustmem_with_tracked_distilled(repo)
        for index in range(120):
            (repo / "knowledge" / "distilled" / f"routine-{index:03d}.md").write_text(
                "noise\n",
                encoding="utf-8",
            )
        (repo / "README.md").write_text("# Test\n\nreal change\n", encoding="utf-8")

        report = gate.build_report(self.workspace)
        trustmem = report["repos"]["trustmem"]

        self.assertTrue(trustmem["dirty"])
        self.assertEqual(trustmem["dirty_count"], 1)
        self.assertEqual(trustmem["dirty_allowlisted_count"], 120)
        self.assertEqual(trustmem["dirty_entries"], [" M README.md"])
        self.assertEqual(len(trustmem["dirty_allowlisted_entries"]), 50)
